# Generated by Django 4.0 on 2022-01-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(upload_to='null=True'),
        ),
    ]
