# Generated by Django 4.0 on 2022-01-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_series', '0002_alter_series_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
